### PR TITLE
Adds support for SSFImpactor Bass Shaker/Exciter-Based Contactor simulation.

### PR DESCRIPTION
**Pull request by kaicherry**
Utilizes ManagedBass.

### CODE REVIEW

**Comment by mjrgh** [comment]
Great - I'll merge this into my fork.  Before I do, it would be good if you could make a few changes:

1.  Minor thing, but it would be good to fill in the xmldoc "///" comments.  Right now they're just copied from the boilerplate.  These can be used to generate the online API doc, so it's good to populate them properly.

2. It doesn't look like you checked in your changes to the project (.csproj) or solution (.sln) files.  You must have at least changed DirectOutput.csproj to add the new files, right?

3. It also looks like there's another file needed for the ManagedBass package - unless that's something built in to .Net, you should check that in as well so it's part of the repos.

4. You should check in Bass.dll as well.  (It has a compatible open-source license allowing it to be included in an MIT-licensed project, right?)

5. Bass.dll should be added to the Costura/Fody set.  I think all you have to do is add it to DirectOutput/Costura32 in the project tree, but please double-check that it's actually included by doing a build, installing on a clean machine **without** a copy of Bass.dll installed and verifying that it still works.  

(We don't want any loose DLLs like Bass.dll in the final install, because .Net has weird problems on a lot of machines resolving paths for loose DLLs.  Everything should be embedded via Costura/Fody.)

Thanks!

**Comment by kaicherry** [comment]
1. Ok, will do
2. I may have forgotten to copy that over (pushed from mac)...I will recheck that DirectOutput.sln in correct one
3. I just installed from NuGet...I am not aware of another rep but Bass.dll?
4. Bass.dll license states it is free to use in non-commercial software/projects/products. I assumed, maybe incorrectly, since VPX uses it it was fine. If not, I can look at redoing this with something else if possible
5. Whoa there fella :) I believe I told you elsewhere "I'm not a Windows Programmer" and I wasn't kidding. I am amazed I got this far. I will try this. Just put in the folder, rebuild...giving that a go.

I've actually made some revisions based on (no pun intended) feedback I got, so maybe better I do this again :) I will look for your thoughts on 3 & 4

**Comment by mjrgh** [comment]
> I just installed from NuGet...I am not aware of another rep but Bass.dll?

The thing that I noticed is the "using ManagedBass" in the .cs file.  I assume that's not a .Net thing but something external.  It might just be a reference to Bass.dll; I just don't know where it's coming from.  Maybe when you check in the .csproj / .sln changes it will become clearer.   (And actually, if you got it from NuGet, then it should have put in the necessary changes to the .csproj/.sln files.  So again, getting those checked in will probably solve it.)

> Whoa there fella :) I believe I told you elsewhere "I'm not a Windows Programmer" and I wasn't kidding. I am amazed I got this far. I will try this. Just put in the folder, rebuild...giving that a go.

If you have any trouble with it let me know and I can try to help out.  I don't remember the details of the Costura/Fody setup myself - there's doc online but it's very skimpy (like most open-source stuff).

> Bass.dll license states it is free to use in non-commercial software/projects/products.

It might be okay, then, but it's always hard to be sure if they're not using one of the standard open-source licenses.  Do they have any contact people we can ask?

**Comment by kaicherry** [comment]
Oh yeah...ManagedBass.Bass is the .Net "wrapper" for Bass.dll; I *was* typing the whole thing, every time and Visual Studio was saying "ok...you don't have to do that" :)

Nope...I seems to be as you said, put in folder, make embedded resource. I've removed Bass.dll from the DirectOutput folder and it's all still working.

I believe they have an email contact for licensing.

**Comment by kaicherry** [comment]
Ok, Take two. How's this? :)

**Comment by mjrgh** [comment]
Thanks - the comment updates are definitely helpful!  And I see the bass.dll files in there too.

It looks like you checked in the .sln files with no changes - I'm not surprised that part didn't change (it rarely does unless you change global settings or add a new project).  

But I still don't see any .csproj updates.  You must have changed at least DirectOutput/DirectOutput.csproj - that has to have been changed by the new files you added and the new references for Bass.dll.  It's weird that git didn't just update that automatically when you committed - git normally just finds all of the diffs to add on its own.  Are you working from a clone of the repos, or doing something more ad hoc?  If you're working from a clone, what do you see if you type 'git status'?  

(Edit: I noticed your remark about copying over from a Mac.  Maybe you should do a wholesale copy of the whole folder to make sure you got everything - if all goes well git should figure out what actually changed based on diff'ing against the repos data.)

**Comment by kaicherry** [comment]
UPDATE - this is not going to work with your grand vision, due to a (likely) small bug in VPX; if the dll is embedded, every custom/original table or table that plays back audio files via a VPX script is stopped with a Bass initialization error. So it is simply not going to work out that way.

I have rebuilt with the same version of the dll  VPX uses, removed the 64-bit one, etc. It appears there is simply a conflict having it "active" before VPX initializes it's own routines.

I really...REALLY don't want to be the guy to start walking down the "*'s DOF Build" path again; is it *possible* to consider this "exception"?  "Everyone" already has the "right" dll already installed anyway if they are using Visual Pinball.

As for .csproj...if that is a file that is modified automatically by the Visual Studio subsystem(s) let me know the location and I can move it over; I modified nothing manually but adding files and changing if or not I want them compiled/embedded in the lower right panel in Visual Studio - the Windows Dev is on a VM...not running on an SSD..so there is pain there putting a full git install on it.

**Comment by mjrgh** [comment]
> if the dll is embedded, every custom/original table or table that plays back audio files via a VPX script is stopped with a Bass initialization error. So it is simply not going to work out that way.

Hmm... so the exact same games work if you **don't** embed the DLL, but fail if it's embedded?

Maybe you could talk to toxie, explain the situation, and see if there's a fix on the VP side that will keep both projects clean.  DOF is such a colossal PITA to configure in the first place that I really, really don't want to make things worse.

> As for .csproj...if that is a file that is modified automatically by the Visual Studio subsystem(s) let me know the location and I can move it over

Right, you modified it when you edited the project tree by adding files, references, etc.  The project tree is the "editor" for this type of file.  

You should see it under the DirectOutput subfolder (that is, DirectOutput/DirectOutput/DirectOutput.csproj - lots of "DirectOutput"s in the path).

It might be good to do a full directory tree listing sorted by date to make sure you've caught everything added since you copied the repos.  Just in case there's one more file we're both forgetting.  These VS projects have lots of little hidden parts that you never think about until you get build errors.

**Comment by kaicherry** [comment]
> > if the dll is embedded, every custom/original table or table that plays back audio files via a VPX script is stopped with a Bass initialization error. So it is simply not going to work out that way.
> 
> Hmm... so the exact same games work if you **don't** embed the DLL, but fail if it's embedded?
> 
100% correct, sir.

> Maybe you could talk to toxie, explain the situation, and see if there's a fix on the VP side that will keep both projects clean. DOF is such a colossal PITA to configure in the first place that I really, really don't want to make things worse.
> 
SAME...*however* :)
Also...toxie?

> > As for .csproj...if that is a file that is modified automatically by the Visual Studio subsystem(s) let me know the location and I can move it over
> 
> Right, you modified it when you edited the project tree by adding files, references, etc. The project tree is the "editor" for this type of file.
> 
> You should see it under the DirectOutput subfolder (that is, DirectOutput/DirectOutput/DirectOutput.csproj - lots of "DirectOutput"s in the path).
> 

Yep, found, figured, pushed, done :)

> It might be good to do a full directory tree listing sorted by date to make sure you've caught everything added since you copied the repos. Just in case there's one more file we're both forgetting. These VS projects have lots of little hidden parts that you never think about until you get build errors.

Are you getting build issues with latest commit?

**Comment by mjrgh** [comment]
> Also...toxie?

The VP guy - he's on vpforums under that ID.  You can should be able to PM him there.

> Are you getting build issues with latest commit?

Haven't tried yet - just wanted to make sure everything's checked in before I start trying to merge it.

**Comment by mjrgh** [comment]
Re Bass.dll: what happens if Bass.dll **isn't present on the system** at all, and you try to use DOF **without** the SSF devices configured?  Will you get an error for the missing DLL?

I'd be okay adding this without Bass.dll embedded provided that it won't create any hassles for anyone who's **not** using SSF.  As long as the SSF code is smart enough not to even attempt to load the DLL when the SSF devices aren't explicitly configured, I think that condition will be met.  But if there's any possibility this is going to create a new class of configuration errors, I think we need to figure out how make the embedding work.

**Comment by kaicherry** [comment]
The code doesn’t run at all if there is no SSFImpactor specified in your Cabinet. I am not sure how not configuring this would cause it to be active. 

Does that happen with other DOF devices?

**Comment by mjrgh** [comment]
> The code doesn’t run at all if there is no SSFImpactor specified in your Cabinet. I am not sure how not configuring this would cause it to be active.

It depends on how the module is configured.  If Base.dll is statically linked, merely including the module will cause .Net to try to load it when DOF is loaded.  

And are you absolutely sure that "the code doesn't run at all" if it's not configured?  C# runs certain code (e.g., static initializers) by virtue of it being present.  DOF explicitly calls certain methods during initialization in every device.  So I'm pretty sure that sections of your code will run regardless of whether the device type is configured.  The question is whether the parts that run whether you want them to or not will also trigger .Net to try to load Bass.dll.  I'd rely on an empirical test here.

**Comment by mjrgh** [comment]
> Refactored class to (help) insure lack of Bass.dll does not impact op… …

Awesome - I'll pull this and give it a try.

**Comment by kaicherry** [comment]
Excellent and thank you. I will pm toxie today and point him at this to see if it would be possible to get VPX looked at so we can get the dll back in .  

Thanks for merging this into the “mainline”.

**Comment by mjrgh** [comment]
I merged it, but it looks like something's missing - I'm getting an error trying to build:

9>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ManagedBass, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
9>D:\per\VisualPinball\DirectOutput\Source\DirectOutput\DirectOutput\Cab\Out\SSF\SSFImpactController.cs(6,7,6,18): error CS0246: The type or namespace name 'ManagedBass' could not be found (are you missing a using directive or an assembly reference?)

Did you say you added ManagedBass as a NuGet package?  Somehow it didn't get into the project - might want to check again if there are any files in your build environment that are timestamped newer than the checkout.

Might be a packages.config file - look to see if you have a DirectOutput/DirectOutput/packages.config file that's been updated.


> I will pm toxie today and point him at this to see if it would be possible to get VPX looked at so we can get the dll back in .

Great - hopefully he can figure out what's going on with that.

**Comment by kaicherry** [comment]
I added DirectOutput/DirectOutput/packages.config to my master branch.

**Comment by mjrgh** [comment]
Great - thanks.  I'll merge that and try again.

**Comment by mjrgh** [comment]
That did the trick!  The build looks good on my machine.  If you have a chance, give it a try - it would be good to sanity-check that my build works for you and that the new SSF features got merged properly.  Here's the MSI:

http://mjrnet.org/pinscape/downloads/DOFSetup-with-SSF.msi

I'll do a little more testing on my end too.  If all looks good on your machine, I'll go ahead and post the update.

**Pull request merged**
