### PR TITLE
Dude's cab Doflinx support & fixes

### PR DESCRIPTION
**Pull request by Vroonsh**
Waiting for beta test on Doflinx & Arnoz Discord side

- Changed handshake to provide real dude's card name
- Provide output mask from Dude's card configuration to Dof during handshake
- Evaluate more precisely configured outputs
- Supports old handshake

### CODE REVIEW

**Comment by mjrgh** [comment]
Sorry - accidentally removed your "draft" status - changed it back, will wait for your final changes.

**Comment by Vroonsh** [comment]
> Sorry - accidentally removed your "draft" status - changed it back, will wait for your final changes.

No worries 😉
I was changing slightly the remap usage as long as it is not finally needed.
When do you plan to release 3.2 ?

**Comment by mjrgh** [comment]
I've already released it as a nominal beta, and I'll just release updates incrementally as needed. I was planning to stop calling it a beta in a few weeks if no significant problems are reported. So no particular schedule - when you're set with this PR I'll roll it into whatever my next update is, or post an update just for it if I don't have any other changes at the time.

**Comment by Vroonsh** [comment]
Beta testers are reporting it's ok on the DirectOutput side, so should be good now :)

**Comment by mjrgh** [comment]
Great - just wanted to let you know I saw the update and will merge it when I get a chance, hopefully in the next few days.

**Comment by mjrgh** [comment]
All merged - thanks!  I'll post a new release update with the changes.

**Pull request merged**
