### PR TITLE
LogLevel support for Log, hide Debug messages until set in globalconfig (easier log analysis)

### PR DESCRIPTION
**Pull request by Vroonsh**
- New LogLevel in Log, default is Warning
- Error, Warning & Debug calls are filtered by LogLevel, Exception & Write are not
- GlobalConfig provide a LogLevel setting to Log (with check & error)
- Cleanup some Write calls -> Warning & Error
- Cleanup some Debug calls -> Write
- Didn't change some Write calls in SSFImpactor to Debug, could be spamming
- Remove compiled switch for Debug in Log & Dude's Cab code

### CODE REVIEW

**Comment by Vroonsh** [comment]
@mjrgh I was wondering if there is some default GlobalConfig.xml to setup to add the new <LogLevel> entry.
Was also wondering if some documentation update is needed about GlobalConfig

**Comment by mjrgh** [comment]
> @mjrgh I was wondering if there is some default GlobalConfig.xml to setup to add the new entry. Was also wondering if some documentation update is needed about GlobalConfig

There is no default GlobalConfig.xml; it just uses defaults if no such file exists.  There's a sample of the B2S global config file in config/examples.  That gets installed in the user's Config/examples folder in the .msi install.

The DOF documentation is here:  https://pinball.weilenmann.net/docu/DirectOutputWIP/index.html.  It includes some coverage of the global config files.  I'd treat everything in the documentation as out-of-date - I don't think SwissLizard ever brought it up to date with R3, and I don't think anyone has touched it since he retired.

That can also be generated from the git tree, but I don't think the generator has worked in a long time.  Take a look at the Documentation and DocumentationHelper subprojects.

**Comment by mjrgh** [comment]
Let's make the default Debug.  I really don't like the idea of making users go through an extra step to get troubleshooting information out of the log.  99% of users (no, I take that back, 100% of users) aren't ever going to look at the log UNLESS there's a problem they're trying to troubleshoot, in which case they're already confused about what's going on, so let's not make it even harder for them by making them go through an extra step to enable the troubleshooting system. Plus, editing an XML file, and then figuring out why the XML file isn't being read, is going to add a whole meta-troubleshooting issue where people have to troubleshoot why they're not getting the troubleshooting information.

And that makes me wonder if we really want to add this at all.  Is it really a problem that anyone has that the log has too much information?  I mean, does the average user ever look at this at all?  I don't think so; they mostly put it in a ZIP file and send it to me or one of you guys, right?  For my own part, I want to see every last detail, every time.

**Comment by Vroonsh** [comment]
Yeah could be defaulted to debug.

I thought about it first while analyzing a lot of users issues on discord. The debug info about shapes generation were quite annoying.

Then, when doing the dude's cab support, I added some debug about what's sent tu the card and wanted to keep it for future debugging. But , while enabling it, I found that again really spammy.
I was also wondering about ssfimpactor which is quite verbose about debug.

I got your point about people not necessarily thinking about enabling the debug log level before investigating by themselves, but those people are usually directly asking on social networks at first.

Was wondering also how much logging could harm dof performances at some point.

I could upgrade the global config editor to expose this level if it could ease the log level switching also.

Anyway the most annoying thing is the bunch of parsing exceptions due to dof lines typos 😅

Let me know what you prefer, I could modify easily.

**Comment by mjrgh** [comment]
I see your point about anything repeated in the loop.  I generally try to avoid any messages myself that get repeated - I try to keep all logging to just initialization and exit stuff.  That kind of thing won't affect performance, obviously.  Anything that I ever add to the main loop is stuff that I just put in for instrumentation purposes and take out before releasing.

Based on that, here's my current thinking.  Maybe ditch the standard warning/error/info/debug levels, and add a Log.Instrumentation() level, which is reserved explicitly for detailed debugging that shouldn't be included in normal use.  (If it's called Log.Debug, people who don't read the comments, which is everyone, will invent their own idea of what it means based on the wording, and before long it'll be de facto equivalent to "Information" or "Warning" or even "Error, but not very serious", and we'll need to go through this exercise again to add another new level that actually means Instrumentation.  Using a name that's really long and hard to type will also be a good deterrent against overuse. :))  Keep all of the existing messages as just Log.Write(), except maybe the ones you mentioned above that are repeated in the main loop.

I'm still pretty uneasy about configuring this through the global config.  One problem is that there are **multiple** global configs, because every calling program gets its own.  And I don't think adding the option to the global config editor will be of much help to most people because it's not exactly automatic at picking files.  The first troubleshooting problem a lot of people have is just figuring out where the damned config files are coming from.

My first thought was that, if it makes sense the real distinction here is debug instrumentation, then maybe just make it conditional on the build configuration - Debug builds get the extra instrumentation messages, Release builds don't.  If you're trying to help someone debug an issue that needs the instrumentation, have them install the debug build.  But that's not great for developers, since all of the instrumentation spam is on all the time.  And that gives me a new idea:  how about NOT making this a matter of "levels", but rather of "keys"?  When you're debugging Dude's Cab code, you want to see all the spammy Dude's Cab messages, but you don't ALSO want to see the spammy Shapes Generation messages and spammy COM port messages or whatever else there is.  You just want to turn on your own spam and leave everyone else's off.  So how about:

Log.Instrumentation("key", "Message...");

The "key" is an arbitrary string key identifying the message type.  Somewhere there's a configuration element containing a list of the keys to enable.  The ones that are enabled get included in the log, everything else gets dropped.

That way, you can leave in your temporary extremely detailed messages, and they'll only get logged when you ask for them.

That still leaves the question of how to enable them.  I guess there are three options: global config file; some other config file; build-time constants.  I'd probably flatly rule out "some other config file" since that's just more points of failure; the only advantage is that it wouldn't be dependent on which host program is in invoking DOF, so it's slightly simpler at that level, but it makes up for it by being yet another file for users to know about.  Build-time constants would be ideal if these messages are ONLY for developer use, but I don't think there'd ever be a need to leave a message in the code at all if you thought it would never ever be needed to debug a user's setup in the field.   So that leaves the global config file.  Much as I don't like adding things there, I think it's okay in this new formulation where it's for detailed instrumentation only, since that should only come up in a case where a user has already found it necessary to ask for help from one of the developers, and the developer is specifically asking for this added information, in which case they can help the user get it set up.  So perhaps a global config element like `<instrumentation>key1;key2</instrumentation>`, where you list the keys you want to enable.

**Comment by mjrgh** [comment]
So that was a long reply - to summarize:

- Let's **not** add the usual "warning/error/info/debug levels"; I don't think they add much value for DOF, since everyone should just run in "debug" mode (under the usual formulation of the "log level" conventions) all the time anyway
- Let's **do** add a Log.Instrumentation("key", "message") that selects **individual** instrumentation message classes
- Document Log.Instrumentation() as being for use **only** for exceptionally spammy messages that are only useful in rare cases where a developer has to get involved and needs extreme detail, emphasizing that the default is always that these messages will never be seen and users will have to go to some trouble to enable them, so chances are that this call is very nearly equivalent to a commented-out line of code
- Almost nothing in the existing code gets converted from Log.Write() to Log.Instrumentation(), just stuff that qualifies as above
- Enable instrumentation messages class keys via a new global config element, something like `<instrumentation>key1;key2</instrumentation>`

**Comment by Vroonsh** [comment]
Yep sounds good, I'll modify the pr that way

**Comment by mjrgh** [comment]
Wonderful, thanks - I think that'll be a great addition.

I actually just added a possibly related spam-reducer, a concept of "one-time" log messages.  I noticed that certain messages tend to get repeated unnecessarily because the code path with the message gets called a lot but always does the same thing, such as loading data from a particular file or returning data from a table. I originally added this as DirectOutputHandler.LogOnce(), because I thought that was the only place I needed it, but of course that was dumb, it has enough general utility that it should be in Log, so I just refactored it as Log.Once().  That's in the commit I just pushed, [89847f4](https://github.com/mjrgh/DirectOutput/commit/89847f463f8918ece8edd2aa4a17580af24b9f62).

**Comment by mjrgh** [comment]
Looks good, thanks!

**Pull request merged**
