### PR TITLE
Feature/vs update

### PR DESCRIPTION
**Pull request by philipellisis**
This will updated DirectOutput to .net 4.8.1 and also update all nuget dependencies to the latest stable versions. I have tested all builds and built the wix project successfully and installed using the MSI for validation and DOF works perfectly, so this should make future development easier as it will run natively on the latest version of visual studio without any issues.

### CODE REVIEW

**Comment by mjrgh** [comment]
That looks great - thanks for doing the testing work.  

The one thing that gives me pause is old Windows versions.  I think there are still significant numbers of cab builders still on ancient versions back to Win 7.  Do you know what the platform support implications of these .Net updates would be?  It might be time to cut 7 and 8/8.1 loose anyway, but if that's what this would do, I should probably solicit comments about it in some of the forums first to see how many people would be affected and how much they'd care.

**Comment by philipellisis** [comment]
> That looks great - thanks for doing the testing work.
> 
> The one thing that gives me pause is old Windows versions. I think there are still significant numbers of cab builders still on ancient versions back to Win 7. Do you know what the platform support implications of these .Net updates would be? It might be time to cut 7 and 8/8.1 loose anyway, but if that's what this would do, I should probably solicit comments about it in some of the forums first to see how many people would be affected and how much they'd care.

I don't think this will have any impact on older windows systems as .net 4.8.1 is compatible all the way down to windows 7 sp1 - https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0 I think it's natively installed so as long as you have kept windows updates going (but I'm not 100% sure of that). I have also worked with DDH69 to ensure that the next version of DOFLinx will be compatible as he has also upgraded to the latest stable .net version. Just replacing the install on my computer didn't cause any conflicts with VPX or popper front end. There are other dependencies in this, but I'm not sure how many of them are still in use at this time, and if there is another 3rd party tool utilizing DOF that is made incompatible, it's probably better to move things in the right direction anyway.

**Comment by philipellisis** [comment]
@mjrgh any additional thoughts?

**Comment by mjrgh** [comment]
Sorry for the delay. Yeah, as long as it's working on Windows 7 I don't think there will be many compatibility complaints.

**Pull request merged**
