### PR TITLE
Refactored to work via Update(), Adds SSFNoid/Faker classes...

### PR DESCRIPTION
**Pull request by kaicherry**
...to facilitate 'hardware' state management in Update for contactors and simulated shaker.
Have a look. This is actually what I would prefer to have in, if possible/reasonable as all "support" will be for this variant; the 'quick and dirty' route threw Exceptions in Update that I don't know were actually harmless. They did not harm *me* but, best to be sure.

Additionally, this one has a "software shaker" - variable speed hooks are in place as well as placeholder for "ramp down/cutoff" for more realism, however this is the "base" and will ignore variability changes at this time.

I hope this isn't a problem as I see you made an installer/were "ready to roll" :/

### CODE REVIEW

**Comment by mjrgh** [comment]
Merged - here's the build for you to try out:

http://mjrnet.org/pinscape/downloads/DOFSetup-with-SSF-20190312.msi

**Comment by kaicherry** [comment]
Thanks, grabbing now.

Also, I know, different place...but that implementation of the Audio Control...*perfect*.

**Comment by kaicherry** [comment]
Ok we've tested this a few times in different places. It's good to go.

Thank you, again.

**Comment by mjrgh** [comment]
FYI, I posted the build release on my Web page.

**Pull request merged**
